/*
Copyright 2019

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/whynowy/knative-source-kinesis/pkg/apis/sources/v1alpha1"
	scheme "github.com/whynowy/knative-source-kinesis/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KinesisSourcesGetter has a method to return a KinesisSourceInterface.
// A group's client should implement this interface.
type KinesisSourcesGetter interface {
	KinesisSources(namespace string) KinesisSourceInterface
}

// KinesisSourceInterface has methods to work with KinesisSource resources.
type KinesisSourceInterface interface {
	Create(*v1alpha1.KinesisSource) (*v1alpha1.KinesisSource, error)
	Update(*v1alpha1.KinesisSource) (*v1alpha1.KinesisSource, error)
	UpdateStatus(*v1alpha1.KinesisSource) (*v1alpha1.KinesisSource, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KinesisSource, error)
	List(opts v1.ListOptions) (*v1alpha1.KinesisSourceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KinesisSource, err error)
	KinesisSourceExpansion
}

// kinesisSources implements KinesisSourceInterface
type kinesisSources struct {
	client rest.Interface
	ns     string
}

// newKinesisSources returns a KinesisSources
func newKinesisSources(c *SourcesV1alpha1Client, namespace string) *kinesisSources {
	return &kinesisSources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kinesisSource, and returns the corresponding kinesisSource object, and an error if there is any.
func (c *kinesisSources) Get(name string, options v1.GetOptions) (result *v1alpha1.KinesisSource, err error) {
	result = &v1alpha1.KinesisSource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kinesissources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KinesisSources that match those selectors.
func (c *kinesisSources) List(opts v1.ListOptions) (result *v1alpha1.KinesisSourceList, err error) {
	result = &v1alpha1.KinesisSourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kinesissources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kinesisSources.
func (c *kinesisSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kinesissources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a kinesisSource and creates it.  Returns the server's representation of the kinesisSource, and an error, if there is any.
func (c *kinesisSources) Create(kinesisSource *v1alpha1.KinesisSource) (result *v1alpha1.KinesisSource, err error) {
	result = &v1alpha1.KinesisSource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kinesissources").
		Body(kinesisSource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kinesisSource and updates it. Returns the server's representation of the kinesisSource, and an error, if there is any.
func (c *kinesisSources) Update(kinesisSource *v1alpha1.KinesisSource) (result *v1alpha1.KinesisSource, err error) {
	result = &v1alpha1.KinesisSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kinesissources").
		Name(kinesisSource.Name).
		Body(kinesisSource).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *kinesisSources) UpdateStatus(kinesisSource *v1alpha1.KinesisSource) (result *v1alpha1.KinesisSource, err error) {
	result = &v1alpha1.KinesisSource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kinesissources").
		Name(kinesisSource.Name).
		SubResource("status").
		Body(kinesisSource).
		Do().
		Into(result)
	return
}

// Delete takes name of the kinesisSource and deletes it. Returns an error if one occurs.
func (c *kinesisSources) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kinesissources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kinesisSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kinesissources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kinesisSource.
func (c *kinesisSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KinesisSource, err error) {
	result = &v1alpha1.KinesisSource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kinesissources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
