apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: cj-3
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory-channel
