
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: kinesis-sample
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: cj-3
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: message-dumper
